# Generated by Django 5.2 on 2025-04-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meteo_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('vent_direction', models.IntegerField()),
                ('vent_moyen_kmh', models.IntegerField()),
                ('vent_rafales_kmh', models.IntegerField()),
                ('temps', models.CharField(max_length=255)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.spot')),
            ],
        ),
    ]
