# Generated by Django 5.2 on 2025-04-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteo',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='temps',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_direction',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_moyen_kmh',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='meteo',
            name='vent_rafales_kmh',
            field=models.IntegerField(null=True),
        ),
    ]
