# Generated by Django 5.2 on 2025-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_alter_meteo_datetime_alter_meteo_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='max_wind_speed_good',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='spot',
            name='max_wind_speed_limit',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='spot',
            name='min_wind_speed_good',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='spot',
            name='min_wind_speed_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='vent_directions_good',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='spot',
            name='vent_directions_limit',
            field=models.JSONField(default=list),
        ),
    ]
