# Generated by Django 5.2 on 2025-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0003_spot_max_wind_speed_good_spot_max_wind_speed_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='max_gusts_speed_good',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='spot',
            name='max_gusts_speed_limit',
            field=models.IntegerField(default=35),
        ),
    ]
