# Generated by Django 5.2 on 2025-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0004_spot_max_gusts_speed_good_spot_max_gusts_speed_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='pluie',
            field=models.FloatField(default=0, null=True),
        ),
    ]
