# Generated by Django 5.2 on 2025-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0005_meteo_pluie'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='flyability_status',
            field=models.CharField(default='FLYABILIY_GOOD', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='meteo',
            name='gusts_speed_status',
            field=models.CharField(default='FLYABILIY_GOOD', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='meteo',
            name='vent_direction_int_to_enum',
            field=models.CharField(default='N', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='meteo',
            name='weather_status',
            field=models.CharField(default='FLYABILIY_GOOD', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='meteo',
            name='wind_direction_status',
            field=models.CharField(default='FLYABILIY_GOOD', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='meteo',
            name='wind_speed_status',
            field=models.CharField(default='FLYABILIY_GOOD', editable=False, max_length=32),
        ),
    ]
