# Generated by Django 5.2 on 2025-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0006_meteo_flyability_status_meteo_gusts_speed_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteo',
            name='vent_direction_int_to_enum',
            field=models.CharField(default='n', editable=False, max_length=3),
        ),
    ]
