# Generated by Django 5.2 on 2025-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0008_alter_meteo_vent_direction_int_to_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='href_beacon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='href_club',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='href_ffvl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='href_map',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
