# Generated by Django 5.1.9 on 2025-05-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0009_spot_href_beacon_spot_href_club_spot_href_ffvl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteo',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
