services:
  - type: web
    name: ca-vole-ou
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cavoleou.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ca-vole-ou-db
          property: connectionString

databases:
  - name: ca-vole-ou-db
    databaseName: ca_vole_ou
    user: ca_vole_ou_user

